include $(AQROOT)/makefile.linux.def

INCLUDE += -I$(VIVANTE_SDK_INC) -I$(VIVANTE_SDK_INC)/HAL -I$(AQROOT)/sdk/inc  -I./ -I$(OVXLIB_DIR)/include/utils -I$(OVXLIB_DIR)/include/client  -I$(OVXLIB_DIR)/include/ops -I$(OVXLIB_DIR)/include -I$(OVXLIB_DIR)/third-party/jpeg-9b

CFLAGS += $(INCLUDE)

################################################################################
# Supply necessary libraries.
LIBS += -L$(VIVANTE_SDK_LIB) -l OpenVX -l OpenVXU -l CLC -l VSC -l m -lGAL
LIBS += $(OVXLIB_DIR)/lib/libjpeg.a
LIBS += -L$(OVXLIB_DIR)/lib -l ovxlib
LIBS +=-L$(LIB_DIR) -l stdc++

#############################################################################
# Macros.
PROGRAM = 1
TARGET_NAME = dncnn
CUR_SOURCE = ${wildcard *.c}
#############################################################################
# Objects.
OBJECTS =  ${patsubst %.c, $(OBJ_DIR)/%.o, $(CUR_SOURCE)}

# installation directory
INSTALL_DIR := ./

################################################################################
# Include the common makefile.

include $(AQROOT)/common.target
