/****************************************************************************
*   Generated by ACUITY 3.8.2
*   Match ovxlib 1.0.3
*
*   Neural Network appliction pre-process header file
****************************************************************************/
#ifndef _VNN_PRE_PROCESS_H_
#define _VNN_PRE_PROCESS_H_

enum
{
    NN_FILE_NONE,
    NN_FILE_TENSOR,
    NN_FILE_QTENSOR,
    NN_FILE_JPG
};

vsi_status vnn_PreProcessDncnn(vsi_nn_graph_t *graph, const char *image_name);

#endif
